/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutBlock: typeof import('./src/components/AboutBlock.vue')['default']
    AccountDialog: typeof import('./src/components/AccountDialog.vue')['default']
    Announcement: typeof import('./src/components/Announcement.vue')['default']
    CarbonAd: typeof import('./src/components/CarbonAd.vue')['default']
    DeleteAccountDialog: typeof import('./src/components/DeleteAccountDialog.vue')['default']
    DeleteDialog: typeof import('./src/components/deleteDialog.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    EditIconDialog: typeof import('./src/components/EditIconDialog.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    H3Description: typeof import('./src/components/H3Description.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    HowToSteps: typeof import('./src/components/HowToSteps.vue')['default']
    IconCard: typeof import('./src/components/iconCard.vue')['default']
    IconDetailsModal: typeof import('./src/components/IconDetailsModal.vue')['default']
    IconDialog: typeof import('./src/components/IconDialog.vue')['default']
    IconUI: typeof import('./src/components/IconUI.vue')['default']
    IsNew: typeof import('./src/components/IsNew.vue')['default']
    LoginDialog: typeof import('./src/components/LoginDialog.vue')['default']
    NativeAd: typeof import('./src/components/NativeAd.vue')['default']
    OptionsMenu: typeof import('./src/components/OptionsMenu.vue')['default']
    ResourcesCard: typeof import('./src/components/ResourcesCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveIconsDialogue: typeof import('./src/components/SaveIconsDialogue.vue')['default']
    Sponsor: typeof import('./src/components/Sponsor.vue')['default']
    StickyBanner: typeof import('./src/components/StickyBanner.vue')['default']
    SubmissionDialog: typeof import('./src/components/SubmissionDialog.vue')['default']
    SubmissionIconPreview: typeof import('./src/components/SubmissionIconPreview.vue')['default']
    UAlert: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCheckbox: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue')['default']
    UDropdownMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UFormField: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UModal: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UploadDialog: typeof import('./src/components/UploadDialog.vue')['default']
    UProgress: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Progress.vue')['default']
    USelectMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.vue')['default']
    UserIconCard: typeof import('./src/components/UserIconCard.vue')['default']
    UserIconCardAdmin: typeof import('./src/components/UserIconCardAdmin.vue')['default']
    UserIconCardLoading: typeof import('./src/components/UserIconCardLoading.vue')['default']
    UserIconGrid: typeof import('./src/components/UserIconGrid.vue')['default']
    USlideover: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Slideover.vue')['default']
    USwitch: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Switch.vue')['default']
    UTextarea: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
    WrittenBy: typeof import('./src/components/WrittenBy.vue')['default']
  }
}
